TKFINV.Web/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TKFINV.Web.BusinessLogic;

namespace TKFINV.Web.Controllers
{
    public class InventoryController : Controller
    {
        //
        // GET: /Inventory/



        //private List<SelectListItem> FactoryItem(string roleid)
        //{
        //    List<SelectListItem> item_list = new List<SelectListItem>();
        //    var data = new AppRoleBLL().getRole();
        //    if (data != null && data.Count() > 0)
        //    {
        //        item_list.Add(new SelectListItem() { Value = "", Text = "Select All" });
        //        foreach (var item in data)
        //        {
        //            item_list.Add(new SelectListItem() { Value = item.ID.ToString(), Text = item.description, Selected = (roleid == item.ID.ToString() ? true : false) });
        //        }
        //    }

        //    return item_list;


        //}


        public ActionResult DataBind(string FactoryCode, string InventoryTypeCode, string ReferenceNumber, string DateRange)
        {
            DateTime dateTo = DateTime.Now.Date;
            DateTime dateFrom = DateTime.Now.Date.AddMonths(-1);
            if (!(DateRange == "" || DateRange ==null))
            {
                var strDateRange = DateRange.Split('-');
                dateFrom = UtilsBLL.ParseDate(strDateRange[0].Trim());
                dateTo = UtilsBLL.ParseDate(strDateRange[1].Trim());
            }
            ViewBag.DateRange = dateFrom.ToString("dd/MM/yyyy") + " - " + dateTo.ToString("dd/MM/yyyy");

            using (tkfinvEntities db = new tkfinvEntities())
            {

                var factoryList = (from f in db.factory where f.isActive == true orderby f.itemOrder select f).ToList();

                var inventoryTypeList = (from q in db.inventorytype orderby q.itemOrder select q).ToList();

                IEnumerable<inventory> inVentoryList = (from q in db.inventory select q).ToList();
               
                inVentoryList = (inVentoryList.Where(x => x.operateDate >= dateFrom && x.operateDate <= dateTo)).ToList();

                inVentoryList = (FactoryCode != "" && FactoryCode != null ? inVentoryList.Where(x => x.FactoryCode == FactoryCode) : inVentoryList).ToList();
                inVentoryList = (ReferenceNumber != "" && ReferenceNumber != null ? inVentoryList.Where(x => x.referenceNumber == ReferenceNumber) : inVentoryList).ToList();

                inVentoryList = (InventoryTypeCode != "" && InventoryTypeCode != null ? inVentoryList.Where(x => x.InventoryTypeCode == InventoryTypeCode) : inVentoryList).ToList();

                ViewBag.inVentoryList = inVentoryList.OrderByDescending(x => x.ID);
                
                
                ViewBag.factoryList = factoryList;

                List<SelectListItem> item_list = new List<SelectListItem>();
                foreach (var item in inventoryTypeList)
                {
                    item_list.Add(new SelectListItem() { Value = item.Code, Text = item.description, Selected = false });
                }
                ViewBag.itemListForDropdowbFactory = item_list;
                
            }
            return View();
        }



        public ActionResult Index(string FactoryCode, string InventoryTypeCode, string ReferenceNumber, string DateRange,string Success)
        {
            if (!(Success == "" || Success == null)) { ViewBag.Success = true; }

            ViewBag.DateRange = "";
            return DataBind(FactoryCode, InventoryTypeCode, ReferenceNumber, DateRange);

        }

        [HttpPost]
        public ActionResult Index(string FactoryCode, string InventoryTypeCode, string ReferenceNumber, string DateRange)
        {
            ViewBag.DateRange = DateRange;
            ViewBag.ReferenceNumber = ReferenceNumber;
            return DataBind(FactoryCode, InventoryTypeCode, ReferenceNumber, DateRange);
        }

        public ActionResult EditInventory(int ID)
        {
            using (tkfinvEntities db = new tkfinvEntities())
            {
                var dbObject = db.inventory.Where(x => x.ID == ID).FirstOrDefault();
                return PartialView(dbObject); 
            }
            
        }
    }
}

TKFINV.Web/Controllers/InventoryInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TKFINV.Web.BusinessLogic;
using System.Text;

namespace TKFINV.Web.Controllers
{
    public class InventoryInController : Controller
    {
        //
        // GET: /InventoryIn/

        public ActionResult DataBind(string FactoryCode, string ReferenceNumber, string DateIn)
        {
            DateTime dateNow = DateTime.Now.Date;
           
            if (DateIn == "" || DateIn == null)
            {
                DateIn = dateNow.ToString("dd/MM/yyyy");
            }
            ViewBag.DateIn = DateIn.Trim(); 

            using (tkfinvEntities db = new tkfinvEntities())
            {
                 ////////////////////////////////////////////
                //get Factory
                var factoryList = (from f in db.factory where f.isActive == true orderby f.itemOrder select f).ToList();


                List<SelectListItem> item_list = new List<SelectListItem>();

                foreach (var item in factoryList)
                {
                    item_list.Add(new SelectListItem() { Value = item.Code, Text = item.description, Selected = false });
                }

                ViewBag.factoryList = item_list;
                ////////////////////////////////////////////////////////////////
                //get product
                var productList = (from f in db.productmodel  orderby f.Code select f).ToList();
                List<SelectListItem> product_list = new List<SelectListItem>();
                
                foreach (var item in productList)
                {
                    product_list.Add(new SelectListItem() { Value = item.Code, Text = item.Code.ToString() +" " +item.productName.ToString(), Selected = false });
                }

                ViewBag.productList = product_list;

                //////////////////////////////////////////////////////////////////////

                //getSize
                var sizeList = (from f in db.productsize orderby f.Code select f).ToList();
                List<SelectListItem> size_list = new List<SelectListItem>();

                foreach (var item in sizeList)
                {
                    size_list.Add(new SelectListItem() { Value = item.Code, Text = item.Code , Selected = false });
                }

                ViewBag.sizetList = size_list;

                ////////////////////////////////////////////////////////////
                //getLocation
                var locationList = (from f in db.location orderby f.Code select f).ToList();
                List<SelectListItem> location_list = new List<SelectListItem>();

                foreach (var item in locationList)
                {
                    location_list.Add(new SelectListItem() { Value = item.Code, Text = item.description, Selected = false });
                }

                ViewBag.locationList = location_list;

                ////////////////////////////////////////////////////////////////

                //get package

                var packageList = (from f in db.packageunit orderby f.Code select f).ToList();
                List<SelectListItem> package_list = new List<SelectListItem>();

                foreach (var item in packageList)
                {
                    package_list.Add(new SelectListItem() { Value = item.Code, Text = item.description, Selected = false });
                }

                ViewBag.packageList = package_list;


            
            
            }
            return View();
        }


        public ActionResult Index(string FactoryCode, string ReferenceNumber, string DateIn)
        {
           // ViewBag.DateRange = "";
            return DataBind(FactoryCode, ReferenceNumber, DateIn);
              
              
             // DataBind(FactoryCode, ReferenceNumber, DateIn);

        }


        [HttpPost]
        public ActionResult Index(string FactoryCode, string ReferenceNumber, string DateIn, string[] ProductCode, string[] ProductSizeCode, string[] LocationCode, string[] PackageCode, string[] Quantity)
        {
            // ViewBag.DateRange = "";
            try
            {
                //Insert record into ddatabase

                if (ReferenceNumber=="")
                {
                    ViewBag.Success = false;
                    ViewBag.ErrorMsg = "กรุณาใส่หมายเลข Po/Inv ก่อนทำการบันทึก";
                    FactoryCode = "";
                    ReferenceNumber = "";
                    DateIn = "";
                    return DataBind(FactoryCode, ReferenceNumber, DateIn);
                }

                //using (tkfinvEntities db = new tkfinvEntities())
                //{

                //    var CheckPO = (from q in db.inventory where q.referenceNumber == ReferenceNumber select q).ToList();
                //    //  inVentorycurrentlyList = (ProductCode[i] != "" ? inVentorycurrentlyList.Where(x => x.ProductModelCode == ProductCode[i]) : inVentorycurrentlyList).ToList();

                //    if (CheckPO.Count() != 0)
                //    {

                //        ViewBag.Success = false;
                //        ViewBag.ErrorMsg = "ไม่สามารถบันทึกได้เนื่องจากหมายเลข Po/Inv :" + ReferenceNumber + " นี้มีอยู่ในระบบแล้ว";
                //        FactoryCode = "";
                //        ReferenceNumber = "";
                //        DateIn = "";
                //        return DataBind(FactoryCode, ReferenceNumber, DateIn);
                //    }

                
                
                //}
              



                int countRow = ProductCode.Count();

                for (int i = 0; i < countRow; i++)
                {

                    if (ProductCode[i] != "" && ProductSizeCode[i] != "" && LocationCode[i] != "" && PackageCode[i] != "" && Quantity[i] != "")
                    {
                        using (tkfinvEntities db = new tkfinvEntities())


                        {

                          //  var dbObj = (from q in db.inventorycurrently select q).ToList();// ดึงข้อมูล existingQuantity จาก inventorycurrently
                            IEnumerable<inventorycurrently> inVentorycurrentlyList = (from q in db.inventorycurrently select q).ToList();
                            inVentorycurrentlyList = (ProductCode[i] != "" ? inVentorycurrentlyList.Where(x => x.ProductModelCode == ProductCode[i]) : inVentorycurrentlyList).ToList();
                            inVentorycurrentlyList = (ProductSizeCode[i] != "" ? inVentorycurrentlyList.Where(x => x.ProductSizeCode == ProductSizeCode[i]) : inVentorycurrentlyList).ToList();
                            inVentorycurrentlyList = (LocationCode[i] != "" ? inVentorycurrentlyList.Where(x => x.LocationCode == LocationCode[i]) : inVentorycurrentlyList).ToList();
                            inVentorycurrentlyList = (PackageCode[i] != "" ? inVentorycurrentlyList.Where(x => x.PackageUnitCode == PackageCode[i]) : inVentorycurrentlyList).ToList();
                           
                            // where q.ProductModelCode == ProductCode[i] && q.ProductSizeCode == ProductSizeCode[i] && q.LocationCode == LocationCode[i] && q.PackageUnitCode == PackageCode[i] 
                            
                            var data = new inventory();
                            if (inVentorycurrentlyList.Count() == 0)
                            {
                                data.existingQuantity = 0;
                            }
                            else
                            {
                                data.existingQuantity = 0;
                                Int32 Qtyexit = 0;
                                foreach (TKFINV.Web.inventorycurrently item in inVentorycurrentlyList)

                                {
                                    Int32.TryParse(item.remaindQuantity, out Qtyexit);
                                    data.existingQuantity = data.existingQuantity + Qtyexit;

                                   
                                }

                            }

                            var user = (TKFINV.Web.Models.LoginUserModel)Session["Appuser"];

                            data.FactoryCode = FactoryCode;
                            data.referenceNumber = ReferenceNumber;
                            data.InventoryTypeCode = "IN";
                            data.ProductModelCode = ProductCode[i];
                            data.ProductSizeCode = ProductSizeCode[i];
                            data.PackageUnitCode = PackageCode[i];
                            data.LocationCode = LocationCode[i];
                            data.quantity = Quantity[i];
                            data.createDate = DateTime.Now;
                            data.operateDate = UtilsBLL.ParseDate(DateIn);
                            data.createBy = user.username;
                            db.Entry(data).State = System.Data.EntityState.Added;
                            db.SaveChanges();

                           
                        }

                    }
                
                
                
                }


                    ViewBag.Success = true;
                    return RedirectToAction("Index", "Inventory", new { Success = true });
                   
            }
            catch(Exception exc)
            {
                ViewBag.Success = false;
                ViewBag.ErrorMsg = exc.Message;
            }


            FactoryCode = "";
            ReferenceNumber = "";
            DateIn = "";


            return DataBind(FactoryCode, ReferenceNumber, DateIn);


            // DataBind(FactoryCode, ReferenceNumber, DateIn);

        }

    }
}

TKFINV.Web/Views/Inventory/EditInventory.cshtml
@model TKFINV.Web.inventory



    @*@Html.DropDownListFor(Model => Model.FactoryCode, (List<SelectListItem>)ViewBag.FactorySelectList, "Select");

    <br />


    @Html.DropDownListFor(Model => Model.ProductModelCode, (List<SelectListItem>)ViewBag.ProductModelSelctList, "Select");

    <br />

    @Html.TextAreaFor(Model => Model.quantity)*@
 test

    <button name="Cancel" class="btn btn-warning">ยกเลิก</button>


<script>

    $("button[name=Cancel]").click(function () {
        var trEdit = $(this).parent('tr');
        trEdit.hide();
        
        var trTarOrg = trEdit.prev('tr');
        trTarOrg.show();


       @*$.ajax({
           url: '@Url.Action("EditInventory", "Inventory")',
           data: { ID: '10' }
       }).done(function (result) {
           trTarget.html(result);
       });*@

        //alert("Ok");
       });
</script>

TKFINV.Web/Views/Inventory/Index.cshtml
@{
    ViewBag.Title = "Inventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{


<link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/bootstrap-daterangepicker/daterangepicker.css")">
<link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/bootstrap-datepicker/css/datepicker.css")">

}


@if (ViewBag.Success != null && (bool)ViewBag.Success)
{

    <div class="alert alert-success">
        <button class="close" data-dismiss="alert">×</button>
        <strong>สำเร็จ!</strong> บันทึกข้อมูลเรียบร้อยแล้ว
    </div>
}


<!-- BEGIN Page Title -->
<div class="page-title">
    <div>
        <h1><i class="icon-home"></i>Inventory</h1>
    </div>


</div>


    <div class="box">
        <div class="box-title">
            <h3><i class="icon-reorder"></i> Simple Form</h3>
            <div class="box-tool">
                <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a>
                
            </div>
        </div>
        <div class="box-content">
            <form  method="post" class="form-horizontal">

                <div class="control-group">
                    <label class="control-label">โรงงาน</label>
                    <div class="controls">
                        <select class="input-large" tabindex="1" name="FactoryCode">
                            @{
                                List<TKFINV.Web.factory> factoryList = (List<TKFINV.Web.factory>)ViewBag.factoryList;
                                                            }
                            @foreach (var item in factoryList)
                            {
                                <option value="@item.Code">@item.description</option>
                            }
                            
                        </select>



                    </div>
                </div>


                <div class="control-group">
                    <label class="control-label">รูปแบบการทำงาน</label>
                    <div class="controls">

                        @Html.DropDownList("InventoryTypeCode", (List<SelectListItem>)ViewBag.itemListForDropdowbFactory, "เลือก", new { @class = "input-xlarge", tabindex = "1" })
                  
                     </div>
                </div>


             
                <div class="control-group">
                    <label class="control-label">ช่วงวันที่</label>
                    <div class="controls">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-calendar"></i></span>
                            @Html.TextBox("DateRange", (object)ViewBag.DateRange, new  {@class="date-range" })

                        </div>
                    </div>
                </div>



              
                <div class="control-group">
                    <label class="control-label">หมายเลข Invoice/PO</label>
                    <div class="controls">
                        @*<input type="text"  class="input-large" name="ReferenceNumber">*@
                        @*<span class="help-inline">Some hint here</span>*@

                        @Html.TextBox("ReferenceNumber", (object)ViewBag.ReferenceNumber, new { @class = "input-large" })
                    </div>
                </div>
               
                 <div class="form-actions">
                    <button type="submit" class="btn btn-primary">ค้นหา</button>
                    
                  
                </div>
            </form>
        </div>
    </div>


@Html.Partial("InventoryTable")

    






<!-- END Page Title -->
@section scripts {

      <script type="text/javascript" src="@Url.Content("~/assets/bootstrap-daterangepicker/daterangepicker.js")"></script>
      <script type="text/javascript" src="@Url.Content("~/assets/bootstrap-datepicker/js/bootstrap-datepicker.js")"></script>
      <script type="text/javascript" src="@Url.Content("~/assets/bootstrap-daterangepicker/date.js")"></script>


        <script type="text/javascript">

            $('#DateRange').daterangepicker({ format: 'dd-MM-yyyy' });


        </script>



}

TKFINV.Web/Views/Inventory/InventoryControl.cshtml
@{
    ViewBag.Title = "InventoryControl";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>InventoryControl</h2>

@section css{





}


<!-- BEGIN Page Title -->
<div class="page-title">
    <div>
        <h1><i class="icon-home"></i>รับสินค้า</h1>
    </div>

</div>



            <div class="box">
    <div class="box-title">
        <h3><i class="icon-reorder"></i> Simple Form</h3>
        <div class="box-tool">
            <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a>

        </div>
    </div>
    <div class="box-content">
        <form method="post" class="form-horizontal">

            <div class="form-actions">
                <button type="submit" class="btn btn-primary">ค้นหา</button>
                <button type="submit" class="btn btn-primary">บันทึกและทำรายการใหม่</button>
                <button type="submit" class="btn btn-primary">กลับ</button>

            </div>


            <div class="control-group">
                <label class="control-label">โรงงาน</label>
                <div class="controls">
                    <select class="input-large" tabindex="1" name="FactoryCode">
                        @{
                            List<TKFINV.Web.factory> factoryList = (List<TKFINV.Web.factory>)ViewBag.factoryList;
                        }
                        @foreach (var item in factoryList)
                        {
                            <option value="@item.Code">@item.description</option>
                        }

                    </select>



                </div>
            </div>


            <div class="control-group">
                <label class="control-label">รูปแบบการทำงาน</label>
                <div class="controls">

                    @Html.DropDownList("InventoryTypeCode", (List<SelectListItem>)ViewBag.itemListForDropdowbFactory, "เลือก", new { @class = "input-xlarge", tabindex = "1" })


                </div>
            </div>



            @*<div class="control-group">
                <label class="control-label">ช่วงวันที่</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-calendar"></i></span>
                        @Html.TextBox("DateRange", (object)ViewBag.DateRange, new { @class = "date-range" })

                    </div>
                </div>
            </div>*@




            <div class="control-group">
                <label class="control-label">หมายเลข Invoice/PO</label>
                <div class="controls">
                    @*<input type="text"  class="input-large" name="ReferenceNumber">*@
                    @*<span class="help-inline">Some hint here</span>*@

                    @Html.TextBox("ReferenceNumber", (object)ViewBag.ReferenceNumber, new { @class = "input-large" })
                </div>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn btn-primary">ค้นหา</button>
                <button type="submit" class="btn btn-primary">ทำรายการรับสินค้า</button>

            </div>
        </form>
    </div>
</div>













    <!-- END Page Title -->
    @section scripts {




    }

TKFINV.Web/Views/Inventory/InventoryTable.cshtml
<div class="box">
    <div class="box-tool" style="float:right;">
        <a href="@Url.Action("Index","InventoryIn")" class="btn btn-lime">นำสินค้าเข้าคลัง</a>
        <button type="submit" class="btn btn-warning">เบิกสินค้า</button>
    </div>
    <div class="box-content">
        <table class="table table-striped table-hover fill-head">
            <thead>
                <tr>
                    <th>#</th>
                    <th>โรงงาน</th>
                    <th>เลขที่ Inv/Po</th>
                    <th>วันที่</th>
                    <th>ผู้ดำเนินการ</th>
                    <th>ประเภทงาน</th>
                    <th style="width: 150px">Action</th>
                </tr>
            </thead>
            <tbody>
                
                
                
                                @{
                                    int i = 0;
                                    foreach (TKFINV.Web.inventory item in ViewBag.inVentoryList)
                                    {
                                        i++;
                                        <tr>
                                            <td>@i</td>
                                            <td>@item.FactoryCode</td>
                                            <td>@item.referenceNumber</td>
                                            <td>@item.operateDate</td>
                                            <td>@item.createBy</td>
                                            <td>@item.InventoryTypeCode</td>
                                            <td>
                                                <button class="btn btn-primary btn-small" name="Edit"  ><i class="icon-edit"></i> Edit</button>
                                                <a class="btn btn-danger btn-small" href="#"><i class="icon-trash"></i> Delete</a>
                                            </td>
                                            
                                        </tr>
                                        <tr style="display:none;">
                                            <td colspan="7">

                                               
                                            </td>
                                        </tr>

                                    }



                                }
            </tbody>
        </table>
    </div>
</div>

<script>

    $("button[name=Edit]").click(function () {
        var trSource = $(this).parent().parent();
        trSource.hide();
        var trTarget = $(this).parent().parent().next('tr');
        trTarget.show();
        $.ajax({
            url: '@Url.Action("EditInventory", "Inventory")',
            data: { ID: '10' }
        }).done(function (result) {
            trTarget.html(result);
        });

        //alert("Ok");
    });


   

</script>