TKFINV.Web/Controllers/ProfileController.cs
using TKFINV.Web.BusinessLogic;
using TKFINV.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TKFINV.Web.Controllers
{
    public class ProfileController : Controller
    {
        //
        // GET: /Profile/

        private List<SelectListItem> AvatarItem()
        {
            List<SelectListItem> item_list = new List<SelectListItem>();
            item_list.Add(new SelectListItem() { Value = "avatar.png", Text = " " });
            item_list.Add(new SelectListItem() { Value = "avatar1.jpg", Text = "avatar1" });
            item_list.Add(new SelectListItem() { Value = "avatar2.jpg", Text = "avatar2" });
            item_list.Add(new SelectListItem() { Value = "avatar3.jpg", Text = "avatar3" });
            item_list.Add(new SelectListItem() { Value = "avatar4.jpg", Text = "avatar4" });
            item_list.Add(new SelectListItem() { Value = "avatar5.jpg", Text = "avatar5" });

            return item_list;


        }

        public ActionResult Index()
        {
            if (Session["Appuser"] == null)
                return RedirectToAction("index", "Login");

            var login_user = (LoginUserModel)Session["Appuser"];
            var appuser = new AppUserBLL().getModelObjectByID(login_user.ID);

            ViewBag.AvatarItem = this.AvatarItem();
            return View(appuser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(applicationuserModel model)
        {
            if (Session["Appuser"] == null)
                return RedirectToAction("index", "Login");

            var login_user = (LoginUserModel)Session["Appuser"];
            model.ID = login_user.ID;
            model.isActive = true;
            model.updateBy = login_user.username;
            model = new AppUserBLL().Update(model);
            ViewBag.MessageAlert = model.MessageResult;
            ViewBag.AvatarItem = this.AvatarItem();
            return View(model);
        }

    }
}

TKFINV.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewBag.Title - Admin</title>
    <meta name="description" content="PCS System">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />

    <!--base css styles-->
    <link rel="stylesheet" href="@Url.Content("~/assets/bootstrap/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/bootstrap/bootstrap-responsive.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/font-awesome/css/font-awesome.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/normalize/normalize.css")">
    
    <!--flaty css styles-->
    <link rel="stylesheet" href="@Url.Content("~/css/flaty.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/flaty-responsive.css")">

    <link rel="shortcut icon" href="@Url.Content("~/img/favicon.png")">
    <script src="@Url.Content("~/assets/modernizr/modernizr-2.6.2.min.js")"></script>


    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" />
    <script src="@Url.Content("~/assets/jquery/jquery-1.10.1.min.js")"></script>
    <script src="@Url.Content("~/assets/nicescroll/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/jquery/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/jquery/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/chosen.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/assets/chosen-bootstrap/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/jquery-ui/jquery-ui.min.js")"></script>
    <link href="@Url.Content("~/assets/jquery-ui/jquery-ui.min.css")" rel="stylesheet" />

    @RenderSection("css", required: false)

</head>
<body class="skin-black">
    <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <!-- BEGIN Navbar -->
    <div id="navbar" class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <!-- BEGIN Brand -->
                <a href="@Url.Action("index","home")" class="brand">
                    <small>
                        <i class="icon-signal"></i>
                        People Counting Solutions
                    </small>
                </a>
                <!-- END Brand -->
                <!-- BEGIN Responsive Sidebar Collapse -->
                <a href="#" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                    <i class="icon-reorder"></i>
                </a>
                <!-- END Responsive Sidebar Collapse -->
                <!-- BEGIN Navbar Buttons -->
                @Html.Partial("~/Views/Shared/_UserProfile.cshtml")
                <!-- END Navbar Buttons -->
            </div>
            <!--/.container-fluid-->
        </div>
        <!--/.navbar-inner-->
    </div>
    <!-- END Navbar -->
    <!-- BEGIN Container -->
    <div class="container-fluid sidebar-gray" id="main-container">
        <!-- BEGIN Sidebar -->
        <div id="sidebar" class="nav-collapse">
            <!-- BEGIN Navlist -->
            @Html.Partial("~/Views/Shared/_Nav_List.cshtml")
            <!-- END Navlist -->
            <!-- BEGIN Sidebar Collapse Button -->
            <div id="sidebar-collapse" class="visible-desktop">
                <i class="icon-double-angle-left"></i>
            </div>
            <!-- END Sidebar Collapse Button -->
        </div>
        <!-- END Sidebar -->
        <!-- BEGIN Content -->
        <div id="main-content">

            @RenderBody()

            <footer>
                <p>@(DateTime.Now.Year) © Push Media Company</p>
            </footer>

            <a id="btn-scrollup" class="btn btn-circle btn-large" href="#"><i class="icon-chevron-up"></i></a>
        </div>
        <!-- END Content -->
    </div>
    <!-- END Container -->
    <!--basic scripts-->
    <script>window.jQuery || document.write('<script src="@Url.Content("~/assets/nicescroll/jquery.min.js")"><\/script>')</script>
    <script src="@Url.Content("~/assets/bootstrap/bootstrap.min.js")"></script>
    @*<script src="@Url.Content("~/assets/nicescroll/jquery.nicescroll.js")"></script>*@
    <!--page specific plugin scripts-->
    <script src="@Url.Content("~/assets/flot/jquery.flot.js")"></script>
    <script src="@Url.Content("~/assets/flot/jquery.flot.resize.js")"></script>
    <script src="@Url.Content("~/assets/flot/jquery.flot.pie.js")"></script>
    <script src="@Url.Content("~/assets/flot/jquery.flot.stack.js")"></script>
    <script src="@Url.Content("~/assets/flot/jquery.flot.crosshair.js")"></script>
    <script src="@Url.Content("~/assets/sparkline/jquery.sparkline.min.js")"></script>

    <!--flaty scripts-->
    <script src="@Url.Content("~/js/flaty.js")"></script>

    @RenderSection("scripts", required: false)

</body>
</html>

TKFINV.Web/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewBag.Title - Admin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />

    @RenderSection("css", required: false)

</head>
<body class="skin-black">
    <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

    <!-- BEGIN Navbar -->
    <div id="navbar" class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <!-- BEGIN Brand -->
                <a href="#" class="brand">
                    <small>
                        <i class="icon-signal"></i>
                        Poeple Counting System
                    </small>
                </a>
                <!-- END Brand -->

                <!-- BEGIN Responsive Sidebar Collapse -->
                <a href="#" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                    <i class="icon-reorder"></i>
                </a>
                <!-- END Responsive Sidebar Collapse -->

                <!-- BEGIN Navbar Buttons -->
                @Html.Partial("~/Views/Shared/_UserProfile.cshtml")
                <!-- END Navbar Buttons -->
            </div>
            <!--/.container-fluid-->
        </div>
        <!--/.navbar-inner-->
    </div>
    <!-- END Navbar -->

    <!-- BEGIN Container -->
    <div class="container-fluid sidebar-gray" id="main-container">
        <!-- BEGIN Sidebar -->
        <div id="sidebar" class="nav-collapse">
            <!-- BEGIN Navlist -->
            @Html.Partial("~/Views/Shared/_Nav_List.cshtml")
            <!-- END Navlist -->

            <!-- BEGIN Sidebar Collapse Button -->
            <div id="sidebar-collapse" class="visible-desktop">
                <i class="icon-double-angle-left"></i>
            </div>
            <!-- END Sidebar Collapse Button -->
        </div>
        <!-- END Sidebar -->

        <!-- BEGIN Content -->
        <div id="main-content">

            @RenderBody()

            <footer>
                <p>@(DateTime.Now.Year) © People Counting System.</p>
            </footer>

            <a id="btn-scrollup" class="btn btn-circle btn-large" href="#"><i class="icon-chevron-up"></i></a>
        </div>
        <!-- END Content -->
    </div>
    <!-- END Container -->
    @RenderSection("scripts", required: false)

</body>
</html>

TKFINV.Web/Views/Shared/_Nav_List.cshtml
@{
    var currentUser = (TKFINV.Web.Models.LoginUserModel)Session["Appuser"];
    var module_group = (currentUser == null ? new List<TKFINV.Web.applicationmodulegroup>() : currentUser.appmodulegrouplist);
    var modules = (currentUser == null ? new List<TKFINV.Web.applicationmodule>() : currentUser.appmodulelist);
    var conname = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString().ToLower() ;
}
<ul class="nav nav-list">
    
    <!-- BEGIN Nav Dynamic -->
    @foreach (var item in module_group)
    {
        
        var item_module = (from q in modules where q.AppModuleGroupID == item.ID orderby q.itemOrder ascending select q).ToList();
        if(item_module != null && item_module.Count > 0)
        {
            if (item.groupName.Equals("Home"))
            {
                foreach (var item_a in item_module)
	            {
		            <li class="@(conname == item_a.moduleName.ToLower()? "active" : "")">
                        <a href="@Url.Action("index", item_a.moduleName)">
                            <i class="@item_a.iconFile"></i>
                            <span>@item_a.description</span>
                        </a>
                    </li>
	            }
            }
            else
            { 
                var active = false;
                foreach (var _a in item_module)
                {
                    if (conname == _a.moduleName.ToLower())
                    {
                        active = true;
                        break;
                    }
                }
                
                <li class="@(active == true ? "active" : "")">
                    <a href="#" class="dropdown-toggle">
                        <i class="@item.iconFile"></i>
                        <span>@item.description</span>
                        <b class="arrow icon-angle-right"></b>
                    </a>

                    <!-- BEGIN Submenu -->
                    <ul class="submenu">
                        @foreach (var item_a in item_module)
	                    {
		                    <li class="@(conname == item_a.moduleName.ToLower()? "active" : "")">
                                <a href="@Url.Action("index", item_a.moduleName)">@item_a.description</a>
		                    </li>
	                    }
                    </ul>
                    <!-- END Submenu -->
                </li>
            }
            
            
            
        }
                       
    }
    <!-- END Nav Dynamic -->

</ul>

TKFINV.Web/Views/Shared/_PartialAlert.cshtml
@model TKFINV.Web.Models.MessageResult


@if (Model != null)
{ 
    <div class="alert alert-@Model.status.ToString()">
        <button class="close" data-dismiss="alert">&times;</button>
        <strong>@Model.status.ToString()!</strong> @Model.message
    </div>
}

TKFINV.Web/Views/Shared/_PartialPagedCompleteScript.cshtml
<script type="text/javascript" src="@Url.Content("~/assets/jquery/jquery.unobtrusive-ajax.min.js")"></script>
<script>
	function PagedOnComplete(obj) {
		console.log(obj);
		var $oncomplete = $('#oncomplete');
		$oncomplete
			.text('โหลดข้อมูลเรียบร้อยแล้ว')
			.css('backgroundColor', 'gray')
			.fadeOut({complete: function () {
				$oncomplete.css('backgroundColor', 'transparent').text('').show();
			}});
	}
</script>

TKFINV.Web/Views/Shared/_UserProfile.cshtml
@{
    var currentUser = new TKFINV.Web.Models.LoginUserModel();
    if (Session["Appuser"] != null)
    {
        currentUser = (TKFINV.Web.Models.LoginUserModel)Session["Appuser"];
    }
}
<ul class="nav flaty-nav pull-right">

    <!-- BEGIN Button User -->
    <li class="user-profile">
        <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
            <img class="nav-user-photo" src="@(currentUser.avatarFile == null ? @Url.Content("~/img/demo/avatar/avatar.png") : @Url.Content("~/img/demo/avatar/") + currentUser.avatarFile)" alt="@currentUser.firstName's Photo" />
            <span class="hidden-phone" id="user_info">@currentUser.firstName</span>
            <i class="icon-caret-down"></i>
        </a>

        <!-- BEGIN User Dropdown -->
        <ul class="dropdown-menu dropdown-navbar" id="user_menu">
            <li class="nav-header">
                <i class="icon-time"></i>
                Logined From @(currentUser.lastLogin.HasValue == true? currentUser.lastLogin.Value.ToString("hh:mm:ss tt") : "")
            </li>

            <li>
                <a href="@Url.Action("index","Profile")">
                    <i class="icon-user"></i>
                    Edit Profile
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="icon-question"></i>
                    Help
                </a>
            </li>

            <li class="divider"></li>

            <li>
                <a href="@Url.Action("Logout","Login")">
                    <i class="icon-off"></i>
                    Logout
                </a>
            </li>
        </ul>
        <!-- BEGIN User Dropdown -->
    </li>
    <!-- END Button User -->
</ul>